title: "Mes Cours"
description: "Cours journaliers accessibles partout"
theme: minima
header_pages:
  - index.md        # Accueil
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-mermaid